export interface SubscriptionProps {
  amount: number;
  authorization: {
    account_name: string | null;
    authorization_code: string;
    bank: string;
    bin: string;
    brand: string;
    card_type: string;
    channel: string;
    country_code: string;
    exp_month: string;
    exp_year: string;
    last4: string;
    reusable: number;
    signature: string;
  };
  createdAt: string;
  cron_expression: string;
  customer: {
    customer_code: string;
    email: string;
    first_name: string | null;
    id: number;
    international_format_phone: string | null;
    last_name: string | null;
    metadata: null;
    phone: string | null;
    risk_action: string;
  };
  domain: string;
  email_token: string;
  id: number;
  integration: number;
  invoice_limit: number;
  metadata: null;
  most_recent_invoice: {
    amount: number;
    authorization: number;
    created_at: string;
    customer: number;
    description: string | null;
    domain: string;
    id: number;
    integration: number;
    invoice_code: string;
    next_notification: string;
    notification_flag: null;
    paid: number;
    paid_at: string;
    period_end: string;
    period_start: string;
    retries: number;
    status: string;
    subscription: number;
    transaction: number;
    updated_at: string;
  };
  next_payment_date: string | null;
  open_invoice: null;
  payments_count: number;
  plan: {
    amount: number;
    createdAt: string;
    currency: string;
    description: string;
    domain: string;
    id: number;
    integration: number;
    interval: string;
    name: string;
    plan_code: string;
    send_invoices: boolean;
    send_sms: boolean;
    updatedAt: string;
  };
  quantity: number;
  split_code: string | null;
  start: number;
  status: string;
  subscription_code: string;
}
