export const SubscriptionPackages = [
  {
    id: 1,
    packageName: "Basic",
    packagePrice: "450",
    // packagePlanCode:"PLN_t75r4ruqwbnm67g",
    packagePlanCode: "PLN_w760t4s5krneblt",
    packageGoods: ["NewsLetter", "Curated Job Search Alerts"],
    link: "/Customer",
  },
  {
    id: 2,
    packageName: "Most Popular",
    packagePrice: "750",
    // packagePlanCode:"PLN_c5f5wxnmq801g0n",
    packagePlanCode: "PLN_j90oifa99gcsgch",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Limited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 3,
    packageName: "Advanced",
    packagePrice: "1100",
    // packagePlanCode:"PLN_dfckl8ypbw5f67z",
    packagePlanCode: "PLN_hrl8wr3ugbxgzpf",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 4,
    packageName: "Premium",
    packagePrice: "1500",
    // packagePlanCode:"PLN_8hrdfu9sjb6fnkb",
    packagePlanCode: "PLN_bc18wio85ryfm5i",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
      // "Access To A Whatsapp Community",
      "Access To A Job Search Accountability Partner",
    ],
    link: "/Customer",
  },
  // {
  //   id: 5,
  //   packageName: "Test 1",
  //   packagePrice: "300",
  //   // packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packageGoods: ["Testing purpses"],
  //   link:"/Customer",
  // },
];
