export const SubscriptionPackages = [
  {
    id: 1,
    packageName: "Basic",
    packagePrice: "450",
    packageFigure:450,
    // packagePlanCode:"PLN_t75r4ruqwbnm67g",
    packagePlanCode: "PLN_w760t4s5krneblt",
    packageGoods: ["NewsLetter", "Curated Job Search Alerts"],
    link: "/Customer",
  },
  {
    id: 2,
    packageName: "Most Popular",
    packagePrice: "750",
    packageFigure:750,
    // packagePlanCode:"PLN_c5f5wxnmq801g0n",
    packagePlanCode: "PLN_j90oifa99gcsgch",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Limited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 3,
    packageName: "Advanced",
    packagePrice: "1,100",
    packageFigure:1100,
    // packagePlanCode:"PLN_dfckl8ypbw5f67z",
    packagePlanCode: "PLN_hrl8wr3ugbxgzpf",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 4,
    packageName: "Premium",
    packagePrice: "1,500",
    packageFigure:1500,
    // packagePlanCode:"PLN_8hrdfu9sjb6fnkb",
    packagePlanCode: "PLN_bc18wio85ryfm5i",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
      // "Access To A Whatsapp Community",
      "Access To A Job Search Accountability Partner",
    ],
    link: "/Customer",
  },
  // {
  //   id: 5,
  //   packageName: "Test 1",
  //   packagePrice: "300",
  //   packageFigure:300,
  //   // packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packageGoods: ["Testing purposes"],
  //   link:"/Customer",
  // },
];

export const AnualSubscriptionPackages=[
  {
    id: 1,
    packageName: "Basic",
    packagePrice: "5,400",
    packageFigure:5400,
    // packagePlanCode:"PLN_ykdu7h1w83po8m7",
    packagePlanCode: "PLN_u6t1jre4vvzdd57",
    packageGoods: ["NewsLetter", "Curated Job Search Alerts"],
    link: "/Customer",
  },
  {
    id: 2,
    packageName: "Most Popular",
    packagePrice: "9,000",
    packageFigure:9000,
    // packagePlanCode:"PLN_hifghlw9f0xki70",
    packagePlanCode: "PLN_8y9hl4dkw3g8b82",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Limited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 3,
    packageName: "Advanced",
    packagePrice: "13,200",
    packageFigure:13200,
    // packagePlanCode:"PLN_uvknfyy0suvh4n1",
    packagePlanCode: "PLN_yqow22yubu57vbd",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 4,
    packageName: "Premium",
    packagePrice: "18,000",
    packageFigure:18000,
    // packagePlanCode:"PLN_ls6nq8avfnl8z11",
    packagePlanCode: "PLN_5ovxmtomzt0vtss",
    packageGoods: [
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
      // "Access To A Whatsapp Community",
      "Access To A Job Search Accountability Partner",
    ],
    link: "/Customer",
  },
  // {
  //   id: 5,
  //   packageName: "Test 1",
  //   packagePrice: "3,600",
  //   packageFigure:3600,
  //   packagePlanCode:"PLN_tjts2u0n8ibayrj",
  //   // packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packageGoods: ["Testing purposes"],
  //   link:"/Customer",
  // },

]

export const AnnualServicesPackages=[
  {

  id: 1,
  packageName: "Whatsapp Community",
  packagePrice: "6,000",
  packageFigure:6000,
  packagePlanCode:"PLN_oojfrfqovsuvbke",
  // packagePlanCode: "PLN_3uu6qivfxwr4vq1",
  packageGoods: ["Encouragement & Accountability", "Networking & Community","Q&A with Experts -"],
  link: "/Customer/whatsappService",
},
]