export const SubscriptionPackages = [
  {
    id: 1,
    packageName: "Basic",
    // packagePrice: "450",
    packagePriceKE: "450",
    packageFigureKE: 450,
    packagePriceUSD: "4.5",
    packageFigureUSD: 4.5,
    // packagePlanCodeKE:"PLN_t75r4ruqwbnm67g",
    packagePlanCodeKE: "PLN_w760t4s5krneblt",
    packagePlanCodeUSD: "PLN_o7hyc72yj0edl1q",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
    ],
    link: "/Customer",
  },
  {
    id: 2,
    packageName: "Most Popular",
    // packagePrice: "750",
    packagePriceKE: "750",
    packageFigureKE: 750,
    packagePriceUSD: "7.5",
    packageFigureUSD: 7.5,
    // packagePlanCode:"PLN_c5f5wxnmq801g0n",
    packagePlanCodeKE: "PLN_j90oifa99gcsgch",
    packagePlanCodeUSD: "PLN_6wsptfgvk56rmcn",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Limited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 3,
    packageName: "Advanced",
    // packagePrice: "1,100",
    // packageFigure:1100,
    packagePriceKE: "1,100",
    packageFigureKE: 1100,
    packagePriceUSD: "11",
    packageFigureUSD: 11,
    // packagePlanCode:"PLN_dfckl8ypbw5f67z",
    packagePlanCodeKE: "PLN_hrl8wr3ugbxgzpf",
    packagePlanCodeUSD: "PLN_w906qnj2l6slpjo",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 4,
    packageName: "Premium",
    // packagePrice: "1,500",
    // packageFigure:1500,
    packagePriceKE: "1,500",
    packageFigureKE: 1500,
    packagePriceUSD: "15",
    packageFigureUSD: 15,
    // packagePlanCode:"PLN_8hrdfu9sjb6fnkb",
    packagePlanCodeKE: "PLN_bc18wio85ryfm5i",
    packagePlanCodeUSD: "PLN_szz8qo79ghakyg1",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
      // "Access To A Whatsapp Community",
      "Access To A Job Search Accountability Partner",
    ],
    link: "/Customer",
  },
  // {
  //   id: 5,
  //   packageName: "Test 1",
  //   packagePriceKE: "300",
  //   packageFigureKE:300,
  //   packagePlanCodeKE:"PLN_h8gh0augbsbo5zv",
  //   // packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packageGoods: ["Testing purposes"],
  //   link:"/Customer",
  // },
];

export const AnualSubscriptionPackages = [
  {
    id: 1,
    packageName: "Basic",
    // packagePrice: "5,400",
    // packageFigure:5400,
    packagePriceKE: "5,400",
    packageFigureKE: 5400,
    packagePriceUSD: "54",
    packageFigureUSD: 54,
    // packagePlanCode:"PLN_ykdu7h1w83po8m7",
    packagePlanCodeKE: "PLN_u6t1jre4vvzdd57",
    packagePlanCodeUSD: "PLN_6inyybc02tguqn1",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
    ],
    link: "/Customer",
  },
  {
    id: 2,
    packageName: "Most Popular",
    // packagePrice: "9,000",
    // packageFigure:9000,
    packagePriceKE: "9,000",
    packageFigureKE: 9000,
    packagePriceUSD: "90",
    packageFigureUSD: 90,
    // packagePlanCode:"PLN_hifghlw9f0xki70",
    packagePlanCodeKE: "PLN_8y9hl4dkw3g8b82",
    packagePlanCodeUSD: "PLN_ltqcoolc63qvos7",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Limited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 3,
    packageName: "Advanced",
    // packagePrice: "13,200",
    // packageFigure:13200,
    packagePriceKE: "13,200",
    packageFigureKE: 13200,
    packagePriceUSD: "132",
    packageFigureUSD: 132,
    // packagePlanCode:"PLN_uvknfyy0suvh4n1",
    packagePlanCodeKE: "PLN_yqow22yubu57vbd",
    packagePlanCodeUSD: "PLN_0aa2obans1gpobd",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
    ],
    link: "/Customer",
  },
  {
    id: 4,
    packageName: "Premium",
    // packagePrice: "18,000",
    // packageFigure:18000,
    packagePriceKE: "18,000",
    packageFigureKE: 18000,
    packagePriceUSD: "180",
    packageFigureUSD: 180,
    // packagePlanCode:"PLN_ls6nq8avfnl8z11",
    packagePlanCodeKE: "PLN_5ovxmtomzt0vtss",
    packagePlanCodeUSD: "PLN_bv2ekt37tfz3fpw",
    packageGoods: [
      "Access To Listed Jobs",
      "NewsLetter",
      "Curated Job Search Alerts",
      "Unlimited Private Email Coaching",
      // "Access To A Whatsapp Community",
      "Access To A Job Search Accountability Partner",
    ],
    link: "/Customer",
  },
  // {
  //   id: 5,
  //   packageName: "Test 1",
  //   packagePrice: "3,600",
  //   packageFigure:3600,
  //   packagePlanCode:"PLN_tjts2u0n8ibayrj",
  //   // packagePlanCode:"PLN_h8gh0augbsbo5zv",
  //   packageGoods: ["Testing purposes"],
  //   link:"/Customer",
  // },
];

export const AnnualServicesPackages = [
  {
    id: 1,
    packageName: "Whatsapp Community",
    // packagePrice: "6,000",
    // packageFigure: 6000,
    packagePriceKE: "6,000",
    packageFigureKE: 6000,
    packagePriceUSD: "60",
    packageFigureUSD: 60,
    // packagePlanCode:"PLN_oojfrfqovsuvbke",
    packagePlanCodeKE: "PLN_3uu6qivfxwr4vq1",
    packagePlanCodeUSD: "PLN_re4cch2cux4mjd1",
    packageGoods: [
      "Encouragement & Accountability",
      "Networking & Community",
      "Q&A with Experts -",
    ],
    link: "/Customer/whatsappService",
  },
];
