export const servicesList=[
    {
        id:1,
        title:"LinkedIn Optimization",
        titleSlug:"linkedin-optimization",
        subheading:"Elevate Your Professional Brand with a 45-Minute LinkedIn Profile Optimization Session",
        img:"https://images.pexels.com/photos/1083792/pexels-photo-1083792.jpeg",
        details:"Your LinkedIn profile is your digital business card, and it has the power to make a lasting impression on potential employers, clients, and professional connections. Join us for a focused 45-minute virtual consultation designed to revamp and optimize your LinkedIn profile for success.",
        benefits:[
            "Tailored Recommendations: Receive personalized insights and recommendations from an experienced professional.",
            "Profile Enhancements: Discover strategies to boost your visibility and credibility on the world's largest professional network.",
            "Keyword Optimization: Learn how to strategically incorporate industry-relevant keywords into your profile to attract the right opportunities.",
            "Networking Tips: Unlock the secrets to expanding your network and maximizing your connections.",
            "Actionable Steps: Walk away with actionable steps and a clearer understanding of how to leverage LinkedIn effectively.",
        ],
        valueProposal:"Invest in your professional growth and make the most out of your LinkedIn presence. Book your 45-minute LinkedIn profile optimization session today and watch your online brand thrive!",
    },
    {
        id:2,
        title:"Students Package",
        titleSlug:"students-package",
        subheading:"Enhance Your Job Application Package with a Comprehensive CV Review and Cover Letter",
        img:"https://images.pexels.com/photos/3466163/pexels-photo-3466163.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Unlock the full potential of your job search with our tailored CV review and cover letter services. This package is designed to empower you in your career journey by ensuring your application materials stand out to potential employers.",
        benefits:[
            "Unlock the full potential of your job search with our tailored CV review and cover letter services. This package is designed to empower you in your career journey by ensuring your application materials stand out to potential employers.",
            "Cover Letter: Craft a compelling cover letter that highlights your strengths and showcases your motivation. We'll help you create a personalized cover letter that makes a strong impression.",
            "Bonus: As a special bonus, we're offering insights into three job openings currently available, giving you a head start in your job search.",
        ],
        valueProposal:"This is the boost your career needs. Take action today to increase your chances of landing your dream job. Book our CV review and cover letter package now",
    },
    {
        id:3,
        title:"ATS CV REVAMP",
        titleSlug:"ats-cv-revamp",
        subheading:"",
        img:"https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Navigating the Applicant Tracking System (ATS) is crucial in today's competitive job market, and we're here to help you excel. Our comprehensive package includes an ATS-compliant CV and a precision-crafted ATS-compliant cover letter, tailored to your specific job application needs.",
        benefits:[
            "ATS-Compliant CV: We'll create a CV that passes through ATS filters with ease, ensuring your qualifications and experience are properly recognized by employers.",
            "ATS-Compliant Cover Letter: Craft a cover letter that complements your CV and grabs the attention of hiring managers. We'll make sure it meets ATS standards and showcases your motivation.",
            "Bonus: As a special bonus, we're offering insights into three job openings currently available, giving you a head start in your job search.",
        ],
        valueProposal:"This is the boost your career needs. Take action today to increase your chances of landing your dream job. Book our ATS CV revamp and cover letter package now!",
    },
    {
        id:4,
        title:"Coaching Session",
        titleSlug:"coaching-session",
        subheading:"Unlock Your Full Potential with a 1-Hour Coaching Session",
        img:"https://images.pexels.com/photos/8761549/pexels-photo-8761549.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Embark on a journey of self-discovery, self-assessment, and goal setting that will transform the way you approach your career and personal growth.",
         benefits:[
            "Discover Your True Self: Gain insights into your strengths, values, and aspirations to better understand your unique path.",
            "Identify Challenges: Pinpoint any obstacles or challenges that may be holding you back from reaching your full potential.",
            "Develop Action Plans: Craft actionable strategies to overcome challenges and turn your goals into reality.",
            "Set Clear Goals: Define concrete, achievable goals that align with your ambitions.",
            "Chart Your Course: Create a roadmap for your personal and professional journey.",
        ],
        valueProposal:"Invest in yourself and take the first step toward a brighter, more fulfilling future. Book your 1-hour coaching session today to start your transformative journey!",
    },
    {
        id:5,
        title:"Interview Preparation",
        titleSlug:"interview-preparation",
        subheading:"Prepare for Success with a 2-Hour Guided Interview Preparation Session",
        img:"https://images.pexels.com/photos/6878705/pexels-photo-6878705.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Your next career move deserves careful planning and strategy. Join us for a comprehensive 2-hour virtual meeting dedicated to interview preparation, where we'll equip you with the tools and confidence you need to succeed.",
         benefits:[
            "Discover Your True Self: Gain insights into your strengths, values, and aspirations to better understand your unique path.",
            "Personalized Guidance: Tailored interview coaching that addresses your specific strengths and areas of improvement.",
            "Mock Interviews: Practice makes perfect! We'll conduct mock interviews to help you refine your responses and build confidence.",
            "Strategic Insights: Gain valuable insights into what hiring managers look for and how to stand out as the ideal candidate.",
            "Feedback and Action Plans: Receive constructive feedback and actionable steps to enhance your interview performance.",
            "Your Path to Success: Chart your unique path to interview success, no matter your industry or role.",
        ],
        valueProposal:"Invest in yourself and take the next step toward landing your dream job. Book your 2-hour guided interview preparation session today and set yourself up for a brighter career future!",
    },
    {
        id:6,
        title:"Consultation Call",
        titleSlug:"consultation-call",
        subheading:"This package includes 30 minutes consultation call on remote work and navigating the remote work landscape",
        img:"https://images.pexels.com/photos/8297125/pexels-photo-8297125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Are you feeling stuck in your career or looking for tailored guidance to elevate your professional journey? this is more than a call—it's your opportunity to invest in yourself and get expert-level guidance. Ready to take the next step? Let's talk!",
         benefits:[
            "Receive a personalized plan that aligns with your remote work goals—whether you're transitioning into remote work, seeking a new remote role, or aiming to excel in your current position.",
            "Gain access to expert tips on how to effectively search for and secure remote job opportunities that fit your skill set and lifestyle. Learn how to stand out in the competitive remote work market.",
            "Learn the essential skills needed to succeed in a virtual environment, from managing time zones and more.",
            "Receive expert guidance on why it is important to improve your LinkedIn profile and other professional platforms to attract remote work opportunities and showcase your skills to potential employers.",
            "Stay ahead with the latest trends and changes in the remote work sector, so you can adapt to new technologies, industries, and opportunities that emerge in the evolving remote workforce.",
            "Ask questions and seek guidance on anything remote working.",
        ],
        valueProposal:"Are you feeling stuck in your career or unsure about your next steps? Let us have an one-on-one and provide tailored advice and actionable strategies to help you navigate your professional challenges.",
    },
    {
        id:7,
        title:"Remote Work Master Class",
        titleSlug:"remote-work-master-class",
        subheading:"The session will be a richly immersive two-hour experience.",
        img:"https://images.pexels.com/photos/4261785/pexels-photo-4261785.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"Ready to thrive in the world of remote work? Join our exclusive Master Class designed for professionals seeking to transition to or excel in remote roles. Whether you're a seasoned remote worker or just starting, don't miss your chance to elevate your career—register now!",
         benefits:[
            "Gain a clear understanding of remote job basics, different employment types, key  and the optimal time zones to target for job applications.",
            "Explore the fastest-growing remote roles, the importance of upskilling, and the best platforms to enhance your skills.",
            "Learn what recruiters value most and discover how to distinguish yourself from other candidate.",
            "Find reliable remote job opportunities, effectively navigate remote job boards, and recognize red flags to avoid scams.",
            "Learn from the industry expert with years of experience in remote work.",
        ],
        valueProposal:"Whether you're a seasoned professional looking to transition to remote roles or a newcomer eager to enter the workforce, our Master Class is designed to equip you with the essential skills, strategies, and insights needed to thrive in a work environment.",
    },
    {
        id:8,
        title:"Introductory Video",
        titleSlug:"introductory-video",
        subheading:"Duration 15 minutes.",
        img:"https://images.pexels.com/photos/6954220/pexels-photo-6954220.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        details:"In the dynamic landscape of remote work, establishing a personal connection can be challenging. This is why most if not all companies, require a 1 minute introductory video. This package will give you pointers and how to address yourself to your future employer!",
         benefits:[
            "Creating a Personal Connection: Get help in introducing yourself —through tone, body language, and expression. This is essential in the remote world where face-to-face interactions are limited.",
            "Establishing Credibility:In the absence of in-person meetings, a video provides a platform to showcase professionalism, expertise, and personality. This package covers this from end to end.",
            "Clear Communication of Expectations: Get a how to introductory video that will allow you to clearly articulate their roles, work styles, and expectations.",
            "Engagement and Accessibility: Get a 15 minutes consultation call for pointers and one round of review.",
        ],
        valueProposal:"An introductory video is more than just a welcome, it's an essential tool for remote workers to establish rapport, communicate effectively, and set the tone for a productive working relationship.",
    },
]