export const TestSubscribedUsers = [
  {
    id: 1,
    roleId: 101,
    email: "alice@example.com",
    firstName: "Alice",
    lastName: "Johnson",
    phoneNumber: "+1234567890",
    status: "Active",
    carrer: "Software Engineer",
  },
  {
    id: 2,
    roleId: 102,
    email: "bob@example.com",
    firstName: "Bob",
    lastName: "Smith",
    phoneNumber: "+1987654321",
    status: "non-renewing",
    carrer: "Product Manager",
  },
  {
    id: 3,
    roleId: 103,
    email: "carol@example.com",
    firstName: "Carol",
    lastName: "Williams",
    phoneNumber: "+1122334455",
    status: "attention",
    carrer: "UX Designer",
  },
  {
    id: 4,
    roleId: 104,
    email: "dave@example.com",
    firstName: "Dave",
    lastName: "Brown",
    phoneNumber: "+1223344556",
    status: "completed",
    carrer: "Data Analyst",
  },
  {
    id: 5,
    roleId: 105,
    email: "eve@example.com",
    firstName: "Eve",
    lastName: "Davis",
    phoneNumber: "+1334455667",
    status: "cancelled",
    carrer: "Marketing Specialist",
  },
];
