export const clientTestimonials=[
    {
        id:1,
        name:"Lavender",
        imgSource:"lavender_hrf5lh",
        details:"Beyond the Savannah's support came at the perfect time. I knew what I wanted, but I didn't know how to get there. With their help, I transitioned into remote work and finally feel aligned in both my career and lifestyle.",
        youtubeLink:"https://youtu.be/51R7fGNN5Iw?si=I3mOkqQyjkaCYNu8",
    },
    {
        id:2,
        name:"Nanji",
        imgSource:"Nanji_wwccn1",
        // details:"Working with Lorraine was amazing. My CV was literally a 0, and with the Lorraine's help it was totally transformed gave me an idea of how a proper CV and cover letter should look and now I am even able to tailor cover letters to suit the jobs I am applying to.",
        details:"I thank God every single day because my life has changed. I am grateful to  Lorraine and Beyond the Savannah for opening her space to teach and train.  I feel like I got more value than what I paid for.",
        youtubeLink:"https://youtu.be/Abhg_zj5WWs?si=jDjec08bqDOD-_3g",
    },
    {
        id:3,
        name:"Nivah",
        imgSource:"Nivah_idmvbz",
        details:"Thank you Lorraine because I got to land a remote job, a dream job, in a company I have been eyeing for so long. It's been a motivation for me because I get to work when taking care of my kids so I don't miss any of their milestones.",
        youtubeLink:"https://youtu.be/M63H554Rnuc?si=ywDqZ_k1tfnf-Ik0",
    },
    {
        id:4,
        name:"Githa De Long",
        imgSource:"Githa_de_Long_iah1y7",
        details:"For me, I would absolutely tell anyone that is looking to change their financial abilities or capabilities, come to Lorraine, because she knows what she is doing, she's talking from experience, she's seen the good, the bad and doesn't gatekeep. She guides well.",
        youtubeLink:"https://youtu.be/cjdns_TzccI?si=eEb9IMJrPYS0IUUR",
    },
    {
        id:5,
        name:"Vicky",
        imgSource:"Vicky_2_fcvtvl",
        details:"Life has never been better for me. It's come full circle, I can breathe now and appreciate life. It was worth it and thank you Lorraine.",
        youtubeLink:"https://youtu.be/WSap3hGt0Pc?si=gnCSwui59TuAH0Br",
    },
    {
        id:6,
        name:"Joyce",
        imgSource:"Joyce_u0swt5",
        details:"If you spend much time in preparation, you will not spend much time getting the opportunity. I applied like today and received a notification for an interview the following day. Of course we had revamped my CV and had a couple of sessions with Lorraine.",
        youtubeLink:"https://youtu.be/MVVjpecYbmg?si=_-imFWFI0UBCKkzF",
    },
    {
        id:7,
        name:"Grace",
        imgSource:"Grace_olkge1",
        details:"It has been a great journey with Lorraine, I feel like you were the trigger to me now starting remote work. Before Beyond the Savannah it was kind of blurry but after I had my CV done, its like something clicked. The conversations we had during our sessions changed my mindset and really made a difference.",
        youtubeLink:"https://youtu.be/m3atseSw-s4?si=yc62z8_sZ_i5NYCU",
    },
    {
        id:8,
        name:"Faith",
        imgSource:"Faith_p3cvuc",
        details:"First of all, remote work is real, its real.I found beyond the Savannah on Tiktok and went to their website to apply. I applied for an NGO internship role and secured it.",
        youtubeLink:"https://youtu.be/vBcQJOxXjls?si=FH3Gb_KviUxNL77N",
    },
    {
        id:9,
        name:"Catherine",
        imgSource:"Catherine_2_w1cxtu",
        details:"I shared my CV and profile that Lorraine worked on beautifully. I started making applications and gaining traction. So guys please, make use of her services, they work, for sure!",
        youtubeLink:"https://youtu.be/ONdqmrIvCrU?si=a8t6YpKYdqfWDVyX",
    },
    {
        id:10,
        name:"Muthoni",
        imgSource:"Muthoni_gtrlfh",
        details:"I am very appreciative of Lorraine. Because if I did not run into her, I wouldn't be where I am right now. If I did not take that video seriously that day, I would not be working remotely right now.",
        youtubeLink:"https://youtu.be/kDMocpeCRx4?si=LO2Dlzqg1ekwefzE",
    },
    {
        id:11,
        name:"Rhandzu",
        imgSource:"Rhandzu_niwj0w",
        details:"I am so grateful to Lorraine and Beyond the Savannah's support. Remote work has given me the chance to be more present in the things I was not really present in. It has given me that opportunity to have that balance of spending time with my family, siblings, partner and to do the things I want to.",
        youtubeLink:"https://youtu.be/R6kFfybGHbY?si=N4Ginci-IUqRCIQ4",
    },
    {
        id:88,
        name:"Sithembelokuhle",
        imgSource:"Sithembelokuhle_ngvziy",
        details:"I am happy with the CV revamp services i especially like that it comes with suggestions on upskilling giving relevant courses to do in order to achieve your goals.",
        youtubeLink:"",
    },
    {
        id:99,
        name:"Martha",
        imgSource:"Martha_gh4n8l",
        details:"Timing was very fast, I loved that I got to clarify few points in my previous cv to help in revamping the new one.",
        youtubeLink:"",
    },
    {
        id:100,
        name:"Loise",
        imgSource:"Loise_d9txt1",
        details:"I'm getting noticed more now and I'm sure its only a matter of time before I land a good job.",
        youtubeLink:"",
    },
    {
        id:111,
        name:"Juliet",
        imgSource:"Juliet_buceu2",
        details:"The CV revamp service was excellent.",
        youtubeLink:"",
    },
]